# --- DB config ---
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_user
spring.datasource.username=marketplace_user_user
spring.datasource.password=StrongPassword123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# --- JWT config (REQUIRED) ---
jwt.secret=cr666N7wIV+JHnv78pWtcfAekL4YXd9gbnJMs8SJ9sI=
jwt.expiration-ms=3600000

# --- Notification service (for later; can point to a \qdummy URL for now) ---
notification.base-url=http://localhost:8081
